#!/usr/bin/env sh

# Description: View a file in hex
# Dependencies: hx (https://github.com/krpors/hx)/xxd and $PAGER
#
# Shell: POSIX compliant
# Author: Arun Prakash Jana

if [ -z "$SPLIT" ] ; then
    open_in_split_pane "$0" "$1"
    exit 0
fi

if ! [ -z "$1" ]; then
    if which hx >/dev/null 2>&1; then
        hx "$1"
    elif which bed >/dev/null 2>&1; then
        bed "$1"
    else
        xxd "$1" | $PAGER
    fi
fi
