#!/usr/bin/env sh

# Borrowed from nnn/plugins/launch to adopt to MacOS

# shellcheck disable=SC2086

get_selected_app() {
    if which fzf >/dev/null 2>&1; then
        # MacOS GUI apps are used to live inside /Applications directory
        fd . /Applications --type d -d 1 -x echo {/} | sort | fzf +m
    else
        exit 1
    fi
}

if app=$( get_selected_app ); then
    open -a "$app" 2>/dev/null 1>/dev/null &

    if ! [ -z "$1" ]; then
        sleep "$1"
    else
        sleep 1
    fi
fi
